### ISSUE TITLE
数据缺少，请问有更新吗？

### ISSUE THREAD

**Issue by 1767773043** [Xuan-ZW/LKPNR#2]
wget -O wikidata-graph.zip https://mind201910.blob.core.windows.net/knowledge-graph/wikidata-graph.zip

**Comment by Xuan-ZW** [comment]
感谢您的关注，该数据原网页已经失效，可以使用我们公布的处理好的数据，https://pan.baidu.com/s/13AVXSWxIuXI14UgKjaSpbg?pwd=siuf#list/path=%2FLKPNR%2Fgraph
